### ISSUE TITLE
Doesn't seem to work for me and there are some settings that are outdated

### ISSUE THREAD

**Issue by gcstang** [Djelibeybi/Portus-On-OracleLinux7#1]
Starting Portus (replace MYSQL ones):
-e PORTUS_PRODUCTION_HOST=mysql 
 -e PORTUS_PRODUCTION_USERNAME=portus 
 -e PORTUS_PRODUCTION_PASSWORD=portus 
 -e PORTUS_PRODUCTION_DATABASE=portus 

Still have issues but these help get further.

**Comment by Djelibeybi** [comment]
Yeah, Portus upstream have changed a LOT of things so this guide is woefully out of date. I'm waiting for them to eventually release 2.3 and then will redevelop this guide. I started working on it during development and stuff just kept changing too much to keep up.

**Comment by Djelibeybi** [comment]
I've added a big, fat warning to the top of the guide too, just so it's clear to everyone.

**Comment by gcstang** [comment]
Thank you, I look forward to your update in the meantime I guess I'll try Harbor unless you can recommend something that might work.

**Comment by Djelibeybi** [comment]
Actually, I just added a note that I've switched to Harbor myself.

**Comment by gcstang** [comment]
Wow! Days of Portus not working and in a few hours Harbor is up and running and a LOT better documented.

**Comment by Djelibeybi** [comment]
I have faith that Portus will be even easier to deploy with the release of 2.3, as it will also be Docker Compose based. But for now, Harbor will do.

Also, Harbor's public interface for images that do not require authentication to pull is (currently) better than Portus' as well.

**Comment by gcstang** [comment]
Do you know if there is a way to put a description on an image in Harbor or
Portus kind of like hub.docker.com has for theirs where it describes what
it is and how it works?

**Comment by Djelibeybi** [comment]
Nope. You'll have to ask over on the Portus and/or Harbor repos. :)
